database.username=root
database.password=qwertyuiop[]12
database.url=jdbc:mysql://127.0.0.1:3306/magiclibrary

hibernate.connection.driver_class=com.mysql.cj.jdbc.Driver
hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
hibernate.hbm2ddl.auto=update
hibernate.format_sql=true
hibernate.show_sql=true